Document: libipmsg
Title: Debian libipmsg Manual
Author: <insert document author here>
Abstract: This manual describes what libipmsg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libipmsg/libipmsg.sgml.gz

Format: postscript
Files: /usr/share/doc/libipmsg/libipmsg.ps.gz

Format: text
Files: /usr/share/doc/libipmsg/libipmsg.text.gz

Format: HTML
Index: /usr/share/doc/libipmsg/html/index.html
Files: /usr/share/doc/libipmsg/html/*.html

  
